{{- if .Values.externalSecret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "firmirror.fullname" . }}
  labels:
    {{- include "firmirror.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef }}
  target:
    name: {{ .Values.externalSecret.targetSecret }}
    creationPolicy: Owner
  {{- with .Values.externalSecret.data }}
  data:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
